version: '2'

services:
  server:
      build: .
      ports:
        - "83:3000"
      links:
        - mongo
      depends_on:
        - mongo

  mongo:
    image: "mongo:3.4"
    restart: always
    volumes:
      - ./backup:/backup
    ports:
      - "27012:27017"
