version: '2'

services:
  server:
      build: .
      ports:
        - "4444:8080"
      links:
        - mongo

      depends_on:
        - mongo

  mongo:
    image: "mongo:3.4"
    restart: always
    volumes:
      - ./data:/data/db
      - ./backup:/backup
    ports:
      - "27012:27017"
